version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/temple
    links:
      - db
    command: bin/rails server
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=topsecret      
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
